In [7]:
# Import the dependencies.
import pandas as pd
import gmaps
import requests
# Import the API key.
from config import g_key

In [8]:
# Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv("weather_data/cities.csv")
city_data_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Rikitea,PF,4/24/21 19:34,-23.1203,-134.9692,78.49,74,100,17.38
1,1,Longyearbyen,SJ,4/24/21 19:34,78.2186,15.6401,24.80,68,75,4.61
2,2,Severo-Kurilsk,RU,4/24/21 19:34,50.6789,156.1250,34.70,97,100,5.99
3,3,Walvis Bay,NaN,4/24/21 19:34,-22.9575,14.5053,59.00,88,0,5.75
4,4,Albany,US,4/24/21 19:32,42.6001,-73.9662,69.01,16,88,7.65

In [9]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

In [10]:
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
temps = []
for temp in max_temp:
    temps.append(max(temp, 0))

In [13]:
# Heatmap of temperature
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
# Assign the figure variable.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=temps, dissipating=False, max_intensity=300, point_radius=4)
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [14]:
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
humidity = city_data_df["Humidity"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [16]:
# Heatmap of cloudiness
locations = city_data_df[["Lat", "Lng"]]
clouds = city_data_df["Cloudiness"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=clouds, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [17]:
# Heatmap of wind speed
locations = city_data_df[["Lat", "Lng"]]
wind = city_data_df["Wind Speed"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=wind, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [18]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [19]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)
# If you have some rows with null values, you'll need to drop them using the 
# dropna() method at the end of your filtering statement when you are creating the new DataFrame.

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Rikitea,PF,4/24/21 19:34,-23.1203,-134.9692,78.49,74,100,17.38
5,5,Saint-Philippe,RE,4/24/21 19:34,-21.3585,55.7679,77.00,83,75,25.32
7,7,Sanchor,IN,4/24/21 19:34,24.7553,71.7722,81.34,29,4,7.78
8,8,Itagiba,BR,4/24/21 19:34,-14.2836,-39.8428,79.32,69,45,4.09
11,11,Matiguas,NI,4/24/21 19:34,12.8373,-85.4622,84.20,48,20,6.40
15,15,Vila Velha,BR,4/24/21 19:34,-20.3297,-40.2925,78.80,69,20,11.50
17,17,Avarua,CK,4/24/21 19:32,-21.2078,-159.7750,80.60,74,20,13.80
22,22,Puerto Ayora,EC,4/24/21 19:34,-0.7393,-90.3518,80.60,78,75,9.22
24,24,Atuona,PF,4/24/21 19:34,-9.8000,-139.0333,80.80,70,2,18.92
29,29,Bambous Virieux,MU,4/24/21 19:34,-20.3428,57.7575,79.00,83,75,17.27

In [20]:
preferred_cities_df.count()

City_ID       179
City          179
Country       179
Date          179
Lat           179
Lng           179
Max Temp      179
Humidity      179
Cloudiness    179
Wind Speed    179
dtype: int64

In [21]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

               City Country  Max Temp      Lat       Lng Hotel Name
0           Rikitea      PF     78.49 -23.1203 -134.9692
5    Saint-Philippe      RE     77.00 -21.3585   55.7679
7           Sanchor      IN     81.34  24.7553   71.7722
8           Itagiba      BR     79.32 -14.2836  -39.8428
11         Matiguas      NI     84.20  12.8373  -85.4622
15       Vila Velha      BR     78.80 -20.3297  -40.2925
17           Avarua      CK     80.60 -21.2078 -159.7750
22     Puerto Ayora      EC     80.60  -0.7393  -90.3518
24           Atuona      PF     80.80  -9.8000 -139.0333
29  Bambous Virieux      MU     79.00 -20.3428   57.7575

In [22]:
# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

In [26]:
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.